[package]
name = "tronic"
version = "0.1.0"
edition = "2024"

[dependencies]
# Base dependencies
tokio = { version = "1.46" }
futures = { version = "0.3" }
http = "1.3"
tower = "0.5"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# gRPC
tonic = "0.13"
prost = "0.13.5" # Tonic 0.13 requires old prost
prost-types = "0.13.5"

# Misc
anyhow = "1.0"
thiserror = "2.0.12"
async-trait = "0.1"
time = { version = "0.3", features = ["local-offset", "macros", "parsing"] }
bon = "3.6.5"

# Crypto
k256 = "0.13"
hex = "0.4.3"
secrecy = "0.10.3"
sha2 = "0.10"
sha3 = "0.10"
bs58 = { version = "0.5", features = ["check"] }
alloy-sol-types = "1.2"
alloy-sol-macro = "1.2"
alloy-primitives = "1.2"
rand = "0.9.1"

# Telemetry
tracing = "0.1"

[build-dependencies]
tonic-build = "0.13"
