allow-branch = ["main"]
consolidate-commits = true
push = true
publish = true

pre-release-commit-message = "chore(release): {{crate_name}} v{{version}}"
tag-name    = "{{prefix}}{{version}}"
tag-message = "chore(release): {{crate_name}} v{{version}}"

# Generate CHANGELOG for the new tag; cliff will put a version section by itself
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
